### ISSUE TITLE
Suggestion: support for nginx or other reverse proxy 

### ISSUE THREAD

**Issue by ghost** [searx/searx-docker#73] opened 2021-03-05 13:00 UTC
Thank you devs for making this easy bundle. 

I think there is a big overlap between folks who want to self host searx and folks who already have a reverse proxy set up. 

Perhaps there could be a version or a documentation teaching how to host this docker image with an existing nginx set up (under a subfolder/subdomain)?

**Comment by unixfox** [comment] 2021-03-05 13:55
duplicate of https://github.com/searx/searx-docker/issues/63

**Closed as completed by unixfox** 2021-03-05 13:55 UTC
