### ISSUE TITLE
 0 1 Docker and Nginx Proxy Manager Upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by poltrian** [searx/searx-docker#78] opened 2021-04-07 08:55 UTC
Hello,

I've been getting this error since this morning. I haven't changed anything from the configuration onwards. Whats going on here?

**Comment by unixfox** [comment] 2021-04-07 09:56
duplicate of https://github.com/searx/searx/discussions/2734

**Closed as completed by unixfox** 2021-04-07 09:56 UTC
