### ISSUE TITLE
New update just broke Searx

### ISSUE THREAD

**Issue by jt196** [searx/searx-docker#53] opened 2020-08-31 16:01 UTC
Folks - running this on Docker and it was running fine till about 1hr ago. Lo and behold just checked and an update was put in around then. Watchtower has updated the latest image. 

The problem is, no search results being shown, and if I go into preferences, no search engines show up. 

Gonna downgrade and turn off Watchtower for now.

**Comment by jt196** [comment] 2020-08-31 16:07
Just did the downgrade and searx/searx:0.17.0-80-a2430154 - is working. 

I'm happy to fire over some logs but nothing showed up in the Docker log. Can recreate it if need be.

**Comment by dalf** [comment] 2020-08-31 16:54
Duplicate of https://github.com/searx/searx/issues/2163

**Closed as completed by dalf** 2020-08-31 16:54 UTC
Labels: duplicate
