### ISSUE TITLE
ERROR: Invalid interpolation format for "command" option in service "searx": "${SEARX_COMMAND:-}"

### ISSUE THREAD

**Issue by airdogvan** [searx/searx-docker#31] opened 2020-04-21 16:59 UTC
after using ./start.sh
Same result of course with docker-compose up.

No idea what that error means.  Have to admit never used "command" in compose file.

Any suggestions welcomed.

**Comment by dalf** [comment] 2020-04-21 19:07
What is your docker-compose version ? it is at be least 1.9.0

**Comment by airdogvan** [comment] 2020-04-22 17:02
version 1.17.1 here running on Ubuntu 18.04 LTS.

Would there be a workaround for my version?

Thanks for the help.

**Comment by brjadams** [comment] 2020-05-19 19:25
Having the same issue, 
```
./start.sh              
use docker-compose.yaml
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```


`docker-compose --version
docker-compose version 1.21.2, build a13347`

And this.


```docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:```

**Comment by ipmanlk** [comment] 2020-06-12 07:45
This is happening because your docker-compose version. Install it from pip. You can use a python virtual environment. In my case, simply installing it to the current user did the trick.

**Comment by dalf** [comment] 2020-07-11 09:57
Duplicate of https://github.com/searx/searx-docker/issues/17

**Closed as completed by dalf** 2020-07-11 09:57 UTC
