### ISSUE TITLE
Change Caddy Port?

### ISSUE THREAD

**Issue by ngx3** [searx/searx-docker#105] opened 2021-09-30 13:32 UTC
I have another service utilizing port 443, is it possible to change the caddy port to 4443? I tried adding it to the script, but it tells me: 
```
ERROR: for caddy  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
```

**Comment by unixfox** [comment] 2021-09-30 17:04
duplicate of https://github.com/searx/searx-docker/issues/63

**Closed as completed by unixfox** 2021-09-30 17:04 UTC

**Comment by ngx3** [comment] 2021-10-01 02:10
Just a note for users reference, the above does not provide a solution. It does not mention Caddy or changing ports without giving off 

> ERROR: for caddy  "host" network_mode is incompatible with port_bindings
> Traceback (most recent call last):
>

**Comment by unixfox** [comment] 2021-10-01 05:29
Never said it was a solution, we just don't support the ability to do that and the feature request for that is tracked in another github issue.
