### ISSUE TITLE
E: The page isn’t redirecting properly

### ISSUE THREAD

**Issue by zevlee** [searx/searx-docker#76] opened 2021-04-05 15:45 UTC
Upon updating to the most recent docker image ``sudo docker pull searx/searx:latest`` (i.e. 1.0.0-26-70895267) there is an issue with accessing the home page of searx instances.

Attempting to visit the home page of the instance https://searx.bar results in an error. In the case of Firefox-based browsers, it's "The page isn't redirecting properly."

However, querying through the URL works just fine as seen here: https://searx.bar/search?q=test

**Comment by zevlee** [comment] 2021-04-05 23:38
I've temporarily set my searx instance to the stable version until the issue is resolved. https://searx.likkle.monster/ happens to be suffering from the issue described in the parent post.

**Comment by cybermcm** [comment] 2021-04-06 07:53
same problem here...

**Comment by unixfox** [comment] 2021-04-06 13:26
Duplicate of #2729

**Closed as completed by unixfox** 2021-04-06 13:26 UTC

**Comment by cybermcm** [comment] 2021-04-06 13:39
https://github.com/searx/searx/issues/2729
