### ISSUE TITLE
when i do ./start.sh ,i can not connect my vps with ssh(22) any more

### ISSUE THREAD

**Issue by zlqlpp** [searx/searx-docker#8] opened 2019-07-31 07:42 UTC
bash +x ./start.sh

when i done that commond . it print  

```
Status: Downloaded newer image for docker.io/searx/searx-checker:latest
Creating morty         ... done
Creating searx-checker ... done
Creating searx         ... done
Creating caddy         ... done
Creating filtron       ... done
Attaching to caddy, filtron, searx-checker, searx, morty
caddy            | 2019/07/31 07:18:19 [INFO][cache:0xc000086960] Started certificate maintenance routine
caddy            | 2019/07/31 07:18:19 [WARNING] Stapling OCSP: no OCSP stapling for [localhost]: no OCSP server specified in certificate
caddy            | Activating privacy features... done.
caddy            | 
caddy            | Serving HTTPS on port 443 
caddy            | https://localhost
caddy            | 
caddy            | 2019/07/31 07:18:19 [INFO] Serving https://localhost 
filtron          | 2019/07/31 07:18:20 13 rules loaded from /etc/filtron/rules.json
filtron          | 2019/07/31 07:18:20 API listens on 10.10.10.3:4041
filtron          | 2019/07/31 07:18:20 Proxy listens on 10.10.10.3:4040
searx-checker    | Sleep 79 seconds
morty            | WARNING: no logs are available with the 'none' log driver
```
and then i can not connect my vps with ssh(22) . how can i do ?

**Comment by dalf** [comment] 2019-07-31 11:52
./start.sh interacts only with docker, but it doesn't change anything about the ssh configuration / connection.

According to your logs, everything has started as intended.

I would check this network connectivity and the system logs.

This issue seems beyond the project scope.

**Comment by dalf** [comment] 2019-08-03 12:01
I close this issue for now: there is not enough information, but feel free to give more details.

**Closed as completed by dalf** 2019-08-03 12:01 UTC
